import axios from '../../axios'
export default{
	namespaced:true,
	state:{
        hotCity:[],
        cities:null,
        nowCity:{
            name:''
        },
        city:{
            name:''
        },
        cityRes:[],
        addr:{
            name:'未选择收货地址'
        }
    },
	actions:{
        getHot({commit}){
            axios.get('/v1/cities?type=hot').then(res=>{
                commit('getHot',res.data)
            })
        },
        getCities({commit}){
            axios.get('/v1/cities?type=group').then(res=>{
                commit('getCities',res.data)
            })
        },
        getNowCity({commit}){
            axios.get('/v1/cities?type=guess').then(res=>{
                commit('getNowCity',res.data)
            })
        },
        getCity({commit},id){
            axios.get('v1/cities/'+id).then(res=>{
                console.log(res.data)
                commit('getCity',res.data)
            })
        },
        search({commit},{keyword,city_id}){
            
            axios.get('v1/pois/',{
                params:{
                    city_id,
                    keyword
                }
            }).then(res=>{
                console.log(res.data)
                commit('search',res.data)
            })
            
        }
    },	
	mutations:{
		getHot(state,hotCity){
            state.hotCity=hotCity
        },
        getCities(state,cities){
            state.cities=cities
        },
        getNowCity(state,city){
            state.nowCity=city
        },
        getCity(state,city){
            state.city=city
        },
        search(state,cityRes){
            state.cityRes=cityRes
        },
        getAddr(state,addr){
            state.addr=addr
        }
	}
}
